version: '3.8'

services:
  flashcard-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flashcard-system
    ports:
      - "80:80"
    restart: always
    # Health check to ensure the application is running correctly
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 1m
      timeout: 10s
      retries: 3
    # For improved security in production
    security_opt:
      - no-new-privileges:true
